services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: IpTvPlaylist
      POSTGRES_USER: IpTvPlaylist_user
      POSTGRES_PASSWORD: IpTvPlaylist_pass
    ports:
      - 5432:5432


  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-server
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@sample.dev
      PGADMIN_DEFAULT_PASSWORD: admin
#      PGADMIN_CONFIG_SERVER_MODE: "False"
#      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - 5050:80
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - ./pgadmin/pgpass:/pgadmin4/pgpass
    entrypoint: >
      /bin/sh -c "
      rootStorage=\"/var/lib/pgadmin/storage/$${PGADMIN_DEFAULT_EMAIL/@/_}\";
      mkdir -p $${rootStorage};
      cp -f /pgadmin4/pgpass $${rootStorage} && chmod 600 $${rootStorage}/pgpass;
      /entrypoint.sh;
      "
    depends_on:
      - postgres